### ISSUE TITLE
bein sport max channels stops after 20-30 seconds.

### ISSUE THREAD

**Issue by wshamroukh** [ghulammurtazaranajee/iptv_bein-sports#2]
bein sport max channels stops after 20-30 seconds. I use VLC player... Do you know how to fix this issue?

**Comment by crazycinou** [comment]
Fixed ?

**Comment by zakaria-didah** [comment]
> Fixed ?

how

**Comment by wshamroukh** [comment]
I don't think so.. I still face this issue... Seems some settings on the server side which we cannot do much about it
